### ISSUE TITLE
how to uninstall ？

### ISSUE THREAD

**Issue by yasenagat** [MarcusSmith/ipaHelper#90]
ps -ef|grep ipaHelper | wc
     266    2740   24519

it start a many threads and makes cpu busy!

I dont know why?

I must execute "ps aux | grep ipaHelper | cut -c 17-22 | xargs kill -9" to kiill all,than it seems normal.

~ how to uninstall ipaHelper?

**Comment by yasenagat** [comment]
501 80755     1   0 五05下午 ??        24:15.68 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Documents/XXX.zip --json --dont-clean
  501 80757 80755   0 五05下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Documents/XXX.zip --json --dont-clean
  501 80758 80755   0 五05下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Documents/XXX.zip --json --dont-clean
  501 80759 80757   0 五05下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80760 80758   0 五05下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80820     1   0 五06下午 ??         3:00.32 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/Alfred_2.7.1_387.zip --json --dont-clean
  501 80822 80820   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/Alfred_2.7.1_387.zip --json --dont-clean
  501 80823 80820   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/Alfred_2.7.1_387.zip --json --dont-clean
  501 80824 80823   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80825 80822   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80865     1   0 五06下午 ??         2:49.54 /bin/bash /usr/bin/ipaHelper clean
  501 80866     1   0 五06下午 ??         2:49.51 /bin/bash /usr/bin/ipaHelper clean
  501 80867     1   0 五06下午 ??         2:50.10 /bin/bash /usr/bin/ipaHelper clean
  501 80870     1   0 五06下午 ??         2:49.50 /bin/bash /usr/bin/ipaHelper clean
  501 80873 80865   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80874 80867   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80875 80865   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80876 80867   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80877 80866   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80878 80873   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80879 80870   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80880 80874   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80881 80875   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80882 80866   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80883 80876   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80884 80870   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80887 80877   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80888 80879   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80889 80882   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80890 80884   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80942     1   0 五06下午 ??         2:48.34 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/lostad-lostad-framework-master.zip --json --dont-clean
  501 80944 80942   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/lostad-lostad-framework-master.zip --json --dont-clean
  501 80945 80942   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/lostad-lostad-framework-master.zip --json --dont-clean
  501 80946 80944   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80947 80945   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80967     1   0 五06下午 ??         2:47.28 /bin/bash /usr/bin/ipaHelper clean
  501 80969 80967   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80970 80967   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80971 80969   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80972 80970   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80986     1   0 五06下午 ??         2:43.58 /bin/bash /usr/bin/ipaHelper clean
  501 80988 80986   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80989 80986   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 80990 80988   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 80991 80989   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81005     1   0 五06下午 ??         2:42.42 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Documents/XXX.zip --json --dont-clean
  501 81007 81005   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Documents/XXX.zip --json --dont-clean
  501 81008 81005   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Documents/XXX.zip --json --dont-clean
  501 81009 81007   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81010 81008   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81026     1   0 五06下午 ??         2:42.38 /bin/bash /usr/bin/ipaHelper clean
  501 81028 81026   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81029 81026   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81030 81028   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81031 81029   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81050     1   0 五06下午 ??         2:37.46 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/XXX_client_web-master.zip --json --dont-clean
  501 81052 81050   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/XXX_client_web-master.zip --json --dont-clean
  501 81053 81050   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/XXX_client_web-master.zip --json --dont-clean
  501 81054 81052   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81055 81053   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81079     1   0 五06下午 ??         2:32.93 /bin/bash /usr/bin/ipaHelper clean
  501 81081 81079   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81082 81079   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81083 81081   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81084 81082   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81095     1   0 五06下午 ??         2:33.17 /bin/bash /usr/bin/ipaHelper clean
  501 81097 81095   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81098 81095   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81099 81097   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81100 81098   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81117     1   0 五06下午 ??         2:33.01 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81119 81117   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81120 81117   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81121 81119   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81122 81120   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81142     1   0 五06下午 ??         2:31.64 /bin/bash /usr/bin/ipaHelper clean
  501 81143     1   0 五06下午 ??         2:32.00 /bin/bash /usr/bin/ipaHelper clean
  501 81144     1   0 五06下午 ??         2:31.81 /bin/bash /usr/bin/ipaHelper clean
  501 81147     1   0 五06下午 ??         2:31.73 /bin/bash /usr/bin/ipaHelper clean
  501 81150 81142   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81151 81142   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81152 81150   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81153 81151   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81154 81143   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81155 81144   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81156 81147   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81158 81143   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81159 81154   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81160 81144   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81161 81147   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81162 81155   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81163 81156   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81164 81158   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81166 81160   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81167 81161   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81220     1   0 五06下午 ??         2:24.59 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/Alfred_2.7.1_387.zip --json --dont-clean
  501 81222 81220   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/Alfred_2.7.1_387.zip --json --dont-clean
  501 81223 81220   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/Downloads/Alfred_2.7.1_387.zip --json --dont-clean
  501 81224 81222   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81225 81223   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81265     1   0 五06下午 ??         2:22.92 /bin/bash /usr/bin/ipaHelper clean
  501 81266     1   0 五06下午 ??         2:23.15 /bin/bash /usr/bin/ipaHelper clean
  501 81267     1   0 五06下午 ??         2:22.94 /bin/bash /usr/bin/ipaHelper clean
  501 81269     1   0 五06下午 ??         2:22.72 /bin/bash /usr/bin/ipaHelper clean
  501 81270     1   0 五06下午 ??         2:23.35 /bin/bash /usr/bin/ipaHelper clean
  501 81271     1   0 五06下午 ??         2:22.84 /bin/bash /usr/bin/ipaHelper clean
  501 81273     1   0 五06下午 ??         2:22.97 /bin/bash /usr/bin/ipaHelper clean
  501 81277     1   0 五06下午 ??         2:23.33 /bin/bash /usr/bin/ipaHelper clean
  501 81279     1   0 五06下午 ??         2:22.79 /bin/bash /usr/bin/ipaHelper clean
  501 81280     1   0 五06下午 ??         2:22.61 /bin/bash /usr/bin/ipaHelper clean
  501 81282     1   0 五06下午 ??         2:22.88 /bin/bash /usr/bin/ipaHelper clean
  501 81283     1   0 五06下午 ??         2:22.99 /bin/bash /usr/bin/ipaHelper clean
  501 81288     1   0 五06下午 ??         2:22.88 /bin/bash /usr/bin/ipaHelper clean
  501 81289     1   0 五06下午 ??         2:22.98 /bin/bash /usr/bin/ipaHelper clean
  501 81292     1   0 五06下午 ??         2:22.60 /bin/bash /usr/bin/ipaHelper clean
  501 81293     1   0 五06下午 ??         2:23.17 /bin/bash /usr/bin/ipaHelper clean
  501 81295     1   0 五06下午 ??         2:22.94 /bin/bash /usr/bin/ipaHelper clean
  501 81299     1   0 五06下午 ??         2:23.49 /bin/bash /usr/bin/ipaHelper clean
  501 81300 81265   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81301 81266   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81302 81267   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81303 81270   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81304 81271   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81305 81265   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81306 81273   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81307 81266   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81308 81300   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81309 81267   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81310 81301   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81311 81302   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81312     1   0 五06下午 ??         2:23.06 /bin/bash /usr/bin/ipaHelper clean
  501 81313 81270   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81314     1   0 五06下午 ??         2:23.28 /bin/bash /usr/bin/ipaHelper clean
  501 81315 81303   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81316 81271   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81317     1   0 五06下午 ??         2:23.24 /bin/bash /usr/bin/ipaHelper clean
  501 81318 81304   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81319 81273   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81320     1   0 五06下午 ??         2:22.83 /bin/bash /usr/bin/ipaHelper clean
  501 81321 81306   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81322 81305   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81327 81280   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81328 81277   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81329 81279   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81331 81307   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81332 81309   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81333 81313   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81335 81316   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81336 81269   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81339 81319   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81340 81282   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81341 81280   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81342 81277   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81343 81279   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81345 81269   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81347 81328   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81348 81329   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81349 81327   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81350 81336   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81351 81341   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81352 81340   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81353 81343   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81354 81342   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81357 81345   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81359 81312   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81361 81312   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81363 81359   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81365 81361   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81371 81283   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81372 81317   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81373 81295   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81374 81371   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81375 81283   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81376 81317   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81377 81372   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81378 81373   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81379 81375   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81380 81376   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81384 81295   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81387 81282   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81390 81292   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81391 81293   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81392 81289   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81396 81384   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81397 81292   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81398 81293   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81401 81288   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81404 81289   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81406 81387   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81408 81390   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81409 81392   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81410 81288   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81414 81314   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81416 81391   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81418 81397   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81419 81398   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81420 81401   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81422 81404   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81426 81410   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81428 81314   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81436 81414   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81443 81299   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81444 81428   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81450 81299   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81451 81443   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81457 81450   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81464 81320   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81472 81320   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81473 81464   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81478 81472   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81664     1   0 五06下午 ??         2:22.39 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81666 81664   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81667 81664   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81668 81666   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81669 81667   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81679     1   0 五06下午 ??         2:22.74 /bin/bash /usr/bin/ipaHelper clean
  501 81680     1   0 五06下午 ??         2:22.49 /bin/bash /usr/bin/ipaHelper clean
  501 81686 81680   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81688 81679   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81689 81680   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81690 81686   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81691 81679   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81692 81688   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81693 81689   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81694 81691   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81727     1   0 五06下午 ??         2:22.63 /bin/bash /usr/bin/ipaHelper clean
  501 81729 81727   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81730 81727   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81731 81729   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81732 81730   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81751     1   0 五06下午 ??         2:20.78 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81753 81751   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81754 81751   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper summary /Users/yasenagat/360�M^Q�M^[M^X/工�M^\/YPT/apktool-1.5.2-mac.zip --json --dont-clean
  501 81755 81753   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81756 81754   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81765     1   0 五06下午 ??         2:20.61 /bin/bash /usr/bin/ipaHelper clean
  501 81766     1   0 五06下午 ??         2:20.66 /bin/bash /usr/bin/ipaHelper clean
  501 81769 81765   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81770 81766   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81771 81765   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81772 81769   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81773 81766   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81774 81770   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81775 81771   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81776 81773   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81792     1   0 五06下午 ??         2:20.04 /bin/bash /usr/bin/ipaHelper clean
  501 81794 81792   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81795 81792   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81796 81794   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81797 81795   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81822     1   0 五06下午 ??         2:20.19 /bin/bash /usr/bin/ipaHelper clean
  501 81824 81822   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81825 81822   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81826 81824   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81827 81825   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81846     1   0 五06下午 ??         2:20.43 /bin/bash /usr/bin/ipaHelper clean
  501 81848 81846   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81849 81846   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81850 81848   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81851 81849   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81864     1   0 五06下午 ??         2:19.93 /bin/bash /usr/bin/ipaHelper clean
  501 81866 81864   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81867 81864   0 五06下午 ??         0:00.00 /bin/bash /usr/bin/ipaHelper clean
  501 81868 81866   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 81869 81867   0 五06下午 ??         0:00.00 tee -a /tmp/ipaHelper.log
  501 82215 76485   0  9:21上午 ttys000    0:00.00 grep ipaHelper

**Comment by MarcusSmith** [comment]
What is it that you are wanting to accomplish with `ps -ef | grep ipaHelper`?
